#!/usr/bin/env bash
# Managed by hugo-base. Do not edit this file: change it in the hugo-base repo.
#
# Front end for the tooling that lives in the hugo-base module. It finds the
# module directory for the version this site pins in go.mod, so the logic it
# runs always matches the base the site actually uses.
#
#   ./hugo-base.sh sync            refresh the files hugo-base manages here
#   ./hugo-base.sh sync --check    fail if any managed file is stale
#   ./hugo-base.sh lint            CSS policy and protected path checks
#   ./hugo-base.sh quality [dir]   axe and Lighthouse against a built site
#   ./hugo-base.sh path            print the module directory
#
# Needs hugo, go and python3 on PATH. Written for bash 3.2 (macOS).

set -euo pipefail

cd "$(dirname "$0")"

find_base() {
  # hugo config mounts prints one JSON object per module, each with its
  # directory on disk. hugo-base is the one holding the sync manifest.
  hugo config mounts | python3 -c '
import json, sys
from pathlib import Path

text = sys.stdin.read()
decoder = json.JSONDecoder()
index = 0
while index < len(text):
    while index < len(text) and text[index] in " \t\r\n":
        index += 1
    if index >= len(text):
        break
    value, index = decoder.raw_decode(text, index)
    directory = value.get("dir")
    if directory and (Path(directory) / "tools" / "managed-files.toml").is_file():
        print(directory.rstrip("/"))
        break
'
}

base=$(find_base)
if [ -z "$base" ]; then
  echo "error: could not find the hugo-base module." >&2
  echo "Check that go.mod requires github.com/bradryanbice/hugo-base and that hugo and go are installed." >&2
  exit 1
fi

command="${1:-}"
[ "$#" -gt 0 ] && shift || true

case "$command" in
  sync)
    python3 "$base/tools/sync.py" --base "$base" --site . "$@"
    ;;
  lint)
    if [ -f "$base/tools/lint/run.sh" ]; then
      bash "$base/tools/lint/run.sh" "$@" .
    else
      echo "error: this hugo-base version does not ship the CSS policy lint yet." >&2
      exit 1
    fi
    ;;
  quality)
    bash "$base/tools/quality/run.sh" "${1:-public}"
    ;;
  path)
    echo "$base"
    ;;
  *)
    echo "usage: ./hugo-base.sh {sync [--check] | lint | quality [dir] | path}" >&2
    exit 2
    ;;
esac
